apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBSubnetGroup
metadata:
  name: silimate-platform-db-subnet-group
  namespace: default
spec:
  name: silimate-platform-db-subnet-group
  subnetIDs:
    - ${EKS_SUBNET_IDS}
  tags: []
