---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cluster-with-iamidentitymappings
  region: us-west-1
iamIdentityMappings:
  - arn: arn:aws:iam::596912105783:role/eksctl-silimate-platform-k8s-node-NodeInstanceRole-89GBJNWWHT9T
    groups:
      - system:masters
    username: admin
    noDuplicateARNs: true
  - arn: arn:aws:iam::596912105783:role/eksctl-silimate-platform-k8s-node-NodeInstanceRole-O6QY7UVFY6NJ
    groups:
      - system:masters
    username: admin
    noDuplicateARNs: true
  - arn: arn:aws:iam::596912105783:root
    groups:
      - system:masters
  - account: "596912105783"
