# Deployment of the containers as a pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: silimate-platform-k8s-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      initContainers:
        - name: flow-init
          image: silimate-flow
          imagePullPolicy: Never
          volumeMounts:
            - name: flows
              mountPath: /app/flows
            - name: steps
              mountPath: /app/steps
          command: [sh, -c, cp -rf /app/flowrepo/* /app/flows/ && cp -rf /app/steprepo/* /app/steps/]
      containers:
        - name: frontend
          image: silimate-platform-frontend
          imagePullPolicy: Never
        - name: nginx
          image: silimate-platform-nginx
          imagePullPolicy: Never
        - name: dashboard
          image: silimate-dashboard
          imagePullPolicy: Never
        - name: backend
          image: silimate-platform-backend
          imagePullPolicy: Never
          volumeMounts:
            - name: flows
              mountPath: /app/flows
            - name: steps
              mountPath: /app/steps
        - name: flow
          image: silimate-flow
          imagePullPolicy: Never
          args: [standalone]
          volumeMounts:
            - name: flows
              mountPath: /app/flows
            - name: steps
              mountPath: /app/steps
      volumes:
        - name: flows
          emptyDir: {}
        - name: steps
          emptyDir: {}
---
# Load balancer to expose the service
apiVersion: v1
kind: Service
metadata:
  name: silimate-platform-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
