# Persistent volume for postgres
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data
---
# Persistent volume claim for postgres
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
# Deployment of the containers as a pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: silimate-platform-k8s-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: postgres
          image: silimate-platform-db
          imagePullPolicy: Never
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
        - name: frontend
          image: silimate-platform-frontend
          imagePullPolicy: Never
        - name: nginx
          image: silimate-platform-nginx
          imagePullPolicy: Never
        - name: dashboard
          image: silimate-dashboard
          imagePullPolicy: Never
        - name: backend
          image: silimate-platform-backend
          imagePullPolicy: Never
        - name: flow
          image: silimate-flow
          imagePullPolicy: Never
          command: ["sh", "-c", "airflow db init && airflow webserver"]
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
# Load balancer for the service
apiVersion: v1
kind: Service
metadata:
  name: silimate-platform-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 80
