# Shared volume claim for all pods
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 32Gi
---
# Shared volume for all pods
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
