apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silimate-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 32Gi
  volumeName: silimate-volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: silimate-volume
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server
    path: /silimate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-claim
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 32Gi
  volumeName: host-volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-volume
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nfs-server
    path: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-claim
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 32Gi
  volumeName: logs-volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-volume
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nfs-server
    path: /silimate/logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdk-claim
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 32Gi
  volumeName: pdk-volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pdk-volume
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: fs-ce57bcc8.efs.us-west-2.amazonaws.com
    path: /