apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 32Gi
  volumeName: share-volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: share-volume
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server
    path: /silimate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-claim
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 32Gi
  volumeName: host-volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-volume
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nfs-server
    path: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cad-claim
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 32Gi
  volumeName: cad-volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cad-volume
spec:
  capacity:
    storage: 32Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: fs-ce57bcc8.efs.us-west-2.amazonaws.com
    path: /