apiVersion: v1
kind: Service
metadata:
  name: silimate-platform-db-service
  labels:
    app: silimate-platform-db-service
spec:
  externalName: ${RDS_ENDPOINT}
  selector:
    app: silimate-platform-db-service
  type: ExternalName
