# Config map to give AWS root user access to the cluster
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::596912105783:root
      groups:
        - system:masters
