# Role to enable access to cluster resources
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: service-reader
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "create", "patch", "update", "get", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
