# EFS storage class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: ${EFS_ID}
  directoryPerms: "700"
---
# Shared volume for all pods
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silimate-claim
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi # this isn't actually used!
---
# Volume for host
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-claim
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi # this isn't actually used!
---
# Volume for pdk
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdk-claim
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi # this isn't actually used!
---
# Volume for logs
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-claim
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi # this isn't actually used!
